# Generated by Django 3.2.8 on 2021-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211104_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('0', 'Triết Học'), ('1', 'Tôn Giáo'), ('2', 'Ngôn Ngữ'), ('3', 'Khoa Học Xã Hội'), ('4', 'Khoa Học Tự Nhiên'), ('5', 'Kỹ Thuật'), ('6', 'Nghệ Thuật'), ('7', 'Văn Học'), ('8', 'Địa Lý - Lịch Sử')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
