# Generated by Django 3.2.8 on 2021-11-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_image',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
    ]
