# Generated by Django 3.2.8 on 2021-11-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_book_image_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_image',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.book'),
        ),
        migrations.AlterField(
            model_name='book_inventory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='store.book'),
        ),
    ]
