# Generated by Django 3.2.8 on 2021-11-08 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211104_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_inventory',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='store.book'),
        ),
    ]
