# Generated by Django 3.2.8 on 2021-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20211111_1130'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='store_book_title_579c41_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['auth'], name='store_book_auth_834e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='book_image',
            index=models.Index(fields=['book'], name='store_book__book_id_e6a7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='book_inventory',
            index=models.Index(fields=['book'], name='store_book__book_id_fb902e_idx'),
        ),
        migrations.AddIndex(
            model_name='book_price',
            index=models.Index(fields=['book'], name='store_book__book_id_3088d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='store_cart_user_id_3a541e_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['book'], name='store_carti_book_id_ccb4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart_session'], name='store_carti_cart_se_4ecfee_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='store_order_user_id_f583af_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['book'], name='store_order_book_id_ab00a1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='store_order_order_i_70b6d9_idx'),
        ),
    ]
