# Generated by Django 3.2.8 on 2021-11-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20211114_1319'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='store_book_title_579c41_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='store_book_auth_834e5a_idx',
        ),
    ]
