# Generated by Django 3.2.8 on 2021-11-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20211114_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đang vận chuyển', 'Đang vận chuyển'), ('Đã hủy', 'Đã hủy'), ('Hoàn thành', 'Hoàn thành')], default='Chờ xác nhận', max_length=100),
        ),
    ]
