# Generated by Django 3.2.8 on 2021-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='birth',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
